site_name: NewtonianPropagator API Reference
site_description: High-Fidelity 6-DOF/7-DOF Astrodynamics & Multi-Body Simulation Engine
site_author: mukid1805
repo_url: https://github.com/mukid1805/NewtonianPropagator
repo_name: mukid1805/NewtonianPropagator

theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - toc.follow
    - toc.integrate # Comment to place TOC outside (the right) sidebar instead of the left
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: false
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            docstring_section_style: table
            signature_crossrefs: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2-3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  - javascripts/mathjax.js

extra_css:
  - stylesheets/extra.css
